import pandas as pd
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.common.by import By
import time
import random

print("Loading the clean job links...")
# 1. Load the CSV generated by our first scraper
df = pd.read_csv("efc_clean_job_links.csv")

# 2. TRAINING WHEELS: We only test the first 5 rows to ensure it works
#df = df.head(5).copy()
#testing complete

# 3. Define the Tech and Finance skills we want to track
tech_skills = ['python', 'sql', 'excel', 'power bi', 'tableau', 'machine learning', 'aws', 'snowflake']
finance_skills = ['risk management', 'compliance', 'trading', 'investment banking', 'quantitative', 'kyc', 'aml', 'portfolio']

# Combine them into one master list
skills_to_track = tech_skills + finance_skills

# Create empty columns for our skills, default them to 0 (False)
for skill in skills_to_track:
    df[skill] = 0

print("Booting up Selenium for Deep Scraping...")
options = webdriver.ChromeOptions()
options.add_argument("--disable-blink-features=AutomationControlled") 
options.add_experimental_option("excludeSwitches", ["enable-automation"]) 
options.add_experimental_option('useAutomationExtension', False)

driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=options)

print("-----------------------------------")
print("Starting the Deep Scrape (Test Batch of 5)...")
print("-----------------------------------")

# 4. Loop through our DataFrame to visit each job page
for index, row in df.iterrows():
    url = row['Job URL']
    title = row['Job Title']
    
    print(f"Scanning Job {index + 1}: {title}")
    
    try:
        driver.get(url)
        # Give the job description time to load
        time.sleep(random.uniform(3.0, 5.0))
        
        # Grab all the text currently visible on the body of the webpage
        page_text = driver.find_element(By.TAG_NAME, "body").text
        
        # Convert it all to lowercase for uniform searching
        page_text_lower = page_text.lower()
        
        # 5. The Keyword Hunt
        for skill in skills_to_track:
            if skill in page_text_lower:
                df.at[index, skill] = 1 # Mark it as found!
                
    except Exception as e:
        print(f"  -> Error reading page: Skipping...")
        continue

driver.quit()

# 6. Save our enriched data to a new test file
output_file = "efc_enriched_testefc_master_data.csv"
df.to_csv(output_file, index=False)

print("-----------------------------------")
print(f"Test complete! Enriched data saved to {output_file}.")
print("\nHere is a preview of what we found (1 = Yes, 0 = No):")
# We print a few select columns just to see if it worked
print(df[['Job Title', 'python', 'sql', 'risk management', 'machine learning']].head())